source 'https://cdn.cocoapods.org/'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

target 'gesturemouse' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  pod 'HandDetector', :path => '../modules/HandDetector'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      "#{Pod::Config.instance.installation_root}/..",
      :mac_catalyst_enabled => false,
      :ccache_enabled => podfile_properties['apple.ccacheEnabled'] == 'true',
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

        # Fix: folly/coro/Coroutine.h not found with react-native-reanimated
        defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        if defs.is_a?(Array)
          defs << 'FOLLY_CFG_NO_COROUTINES=1' unless defs.include?('FOLLY_CFG_NO_COROUTINES=1')
        else
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = [(defs || '$(inherited)'), 'FOLLY_CFG_NO_COROUTINES=1']
        end

        hs = config.build_settings['HEADER_SEARCH_PATHS']
        if hs.is_a?(Array)
          config.build_settings['HEADER_SEARCH_PATHS'] = hs + [
            '"$(PODS_ROOT)/../../node_modules/react-native/ReactCommon"',
            '"$(PODS_ROOT)/../../node_modules/react-native/ReactCommon/runtimeexecutor"',
          ]
        else
          base = hs || '$(inherited)'
          config.build_settings['HEADER_SEARCH_PATHS'] = "#{base} \"$(PODS_ROOT)/../../node_modules/react-native/ReactCommon\" \"$(PODS_ROOT)/../../node_modules/react-native/ReactCommon/runtimeexecutor\""
        end
      end
    end
  end
end
